# Generated by Django 5.2.11 on 2026-02-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
