# Generated by Django 5.2.11 on 2026-02-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderitem_latitude_orderitem_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
